name: food_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.3.0
  flutter_cache_manager: ^3.3.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/food.login.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/
